from typing import Literal
# This file will be erased and rewritten every time a new Lumerical FDTD project file is created or loaded.

Materials = Literal[
    'Ag (Silver) - Johnson and Christy',
    'Al (Aluminium) - CRC',
    'Ag (Silver) - Palik (0-2um)',
    'W (Tungsten) - Palik',
    'InAs - Palik',
    'TiO2 (Titanium Dioxide) - Sarkar',
    'Cr (Chromium) - CRC',
    '5CB - Li',
    'Ge (Germanium) - Palik',
    'Si3N4 (Silicon Nitride) - Luke',
    '5PCH - Li',
    'TiO2 (Titanium Dioxide) - Kischkat',
    'Ag (Silver) - CRC',
    'PEC (Perfect Electrical Conductor)',
    'Al2O3 - Palik',
    'Al (Aluminium) - Palik',
    'E44 - Li',
    'W (Tungsten) - CRC',
    'TiO2 (Titanium Dioxide) - Devore',
    'Si3N4 (Silicon Nitride) - Phillip',
    'Sn (Tin) - Palik',
    'Cr (Chromium) - Palik',
    'Fe (Iron) - Palik',
    'MLC-6608 - Li',
    'C (graphene) - Falkovsky (mid-IR)',
    'Pt (Platinum) - Palik',
    'Au (Gold) - CRC',
    'Si (Silicon) - Palik',
    'Fe (Iron) - CRC',
    'SiO2 (Glass) - Palik',
    'Si3N4 (Silicon Nitride) - Kischkat',
    'Pd (Palladium) - Palik',
    'In (Indium) - Palik',
    'Ni (Nickel) - CRC',
    'MLC-9200-100 - Li',
    'InP - Palik',
    'MLC-9200-000 - Li',
    'Ni (Nickel) - Palik',
    'Cu (Copper) - CRC',
    'Ge (Germanium) - CRC',
    'etch',
    'Au (Gold) - Palik',
    'Ti (Titanium) - Palik',
    'TiN - Palik',
    'TiO2 (Titanium Dioxide) - Siefke',
    'Ti (Titanium) - CRC',
    'H2O (Water) - Palik',
    'Au (Gold) - Johnson and Christy',
    'GaAs - Palik',
    'V (Vanadium ) - CRC',
    '6241-000 - Li',
    'Cu (Copper) - Palik',
    'Ta (Tantalum) - CRC',
    'E7 - Li',
    'Rh (Rhodium) - Palik',
    'Ag (Silver) - Palik (1-10um)',
    'TL-216 - Li',
    '<Object defined dielectric>',
	]